### ISSUE TITLE
Mark homework 2 of Youjia Zhou

### ISSUE THREAD

**Issue by zhou325** [zhou325/stat679work#4]
Professor @cecileane,
This is the revision SHA for my homework 2: 197c223ba9a505b6ea36b7c1856328ef19f7a028

I've wrote all explanations and details in [readme.md](https://github.com/zhou325/stat679work/blob/master/hw2/readme.md)

Please let me know if there is any problem.
Thank you very much!

Best,
Youjia

**Comment by cecileane** [comment]
Hi Youjia,

Very nice job! More details below.

## overall presentation

Your work is nicely organized with different folders for scripts, and input/output files. In your readme file, your section "code snapshot" shows all of the code, so it's not really a snapshot. You don't need this section. If you want to highlight some important little parts of the code, then yes, a "code snapshot" section is a good idea. You made great use of the markdown style. Your readme file is great and has great explanations.

## running your script

It's really nice that the output could go to STDOUT or any file name. Unfortunately, the output has extra quoted commas in the cells that should have nothing. I got an output that started like this:

    "Index","Date Time","Temperature","Energy (Wh/1000)"
    1,07/29/16 10:26:34 AM,72.86,","
    2,07/29/16 11:26:34 AM,73.92,","
    3,07/29/16 12:26:34 PM,73.98,","
    ...
    13,07/29/16 10:26:34 PM,73.27,","
    14,07/29/16 11:26:34 PM,73.45,9.468
    15,07/30/16 12:26:34 AM,72.30,","

instead of this, to have empty cells where there is no energy value:

    "Index","Date Time","Temperature","Energy (Wh/1000)"
    1,07/29/16 10:26:34 AM,72.86,
    2,07/29/16 11:26:34 AM,73.92,
    3,07/29/16 12:26:34 PM,73.98,
    ...
    13,07/29/16 10:26:34 PM,73.27,
    14,07/29/16 11:26:34 PM,73.45,9.468
    15,07/30/16 12:26:34 AM,72.30,

(line 112 in your script should be modified).
The script itself did not give much help to run it. For example, with only 1 argument or no argument, the error did not say what the problem was:

```shell
$ python scripts/hw2.py --help
Traceback (most recent call last):
  File "scripts/hw2.py", line 5, in <module>
    energy = sys.argv[2]
IndexError: list index out of range
```

You do test for at least 2 or 3 arguments, but you do it too late because you need the arguments before you test that they exist: you have this on lines 4-5:

```python
temperature= sys.argv[1]
energy = sys.argv[2]
```

and you test for the existence of arguments after (lines 6-11):

```python
if(len(sys.argv) == 4):
    ...
else:
    raise IOError("The number of arguments must be 2 or 3.")
```

It would have been best to use the argparse library to read arguments.

## about your code

It's good that you have several functions, to break the problem down into smaller problems and to make the algorithm more readable. You could have done this further, because your function `merging_data` is very long.

It's great that you check the assumption that energy values are associated with midnight times.

Nice use of regular expressions to parse the times.

On lines 60-67, you have extra indentation that did not need. You have this if/elif/else block:

```python
   if(check_time(energy_time) == False):
       print("Error: all energy dates should be at 00:00:00, Wisconsin time")
       return
   elif(is_sorted(energy_date) == False):
       print("Error: energy dates should be sorted")
       return
   else:
       # deal with the temperature file
       ... (real stuff here)
```

3 things here:
- to raise an error, you should raise an exception (=error) with `raise Exception("Error: all energy dates ...")` instead of printing the error message (like you would print any good message) and then `return` nothing. The function will have a good exit status, as if no error had occurred.
- use the True/False values as they are, no need to see if a False value is False or not
- if there is an error: the function will `return`. So nothing else below will be executed anyway. You did not need to put the real stuff inside an `else` block, like this:

```python
if not check_time(energy_time): # will be True if check_time(energy_time) is False
    raise Exception("Error: all energy dates should be at 00:00:00, Wisconsin time")
if not is_sorted(energy_date): # will be True if is_sorted(energy_date) is False
    raise Exception("Error: energy dates should be sorted")

# deal with the temperature file
... (real stuff here)
```

Great use of a custom key to sort your temperature list! You used a function that you called `getKey`. While this name matches the way you use it (as argument `key` for `sort()`), this name is not informative about what the function is going. It does not help the reader understand how you are sorting your temperature list. A better name would have been `getTime`, and a comment in the definition of this function could have said that `item[2]` (line 71) contains the time for each line in the temperature list. Variable and function names are important: to write code for humans!

Very nice work overall.
